# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 21:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userui', '0002_auto_20171019_0358'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
